version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_DSN=postgresql://user:password@postgres:5432/scaling_db
    depends_on:
      - redis
      - postgres

  processor:
    build: 
      context: .
      dockerfile: docker/processor/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_DSN=postgresql://user:password@postgres:5432/scaling_db
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: scaling_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
